// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zecnstlasykrdlvclgya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplY25zdGxhc3lrcmRsdmNsZ3lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NjMxMDksImV4cCI6MjA1NzUzOTEwOX0.gC86q5XxhWT_w2ERx1d8_WXeZdI3ZDy5iQ60YNf_zWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);